# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

resources:
  - repo: self

variables:
  tag: "$(Build.BuildId)"

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: "dockerservice"
              repository: "nagashreeshetty/newpythonwebapp"
              command: "buildAndPush"
              Dockerfile: "**/Dockerfile"
              tags: |
                $(tag)
  - stage: Provision
    display_name: "Terraform on Azure"
    dependsOn: Build
    jobs:
      - job: Provision
        display name: "Provision Container "
        pool:
          vmImage: ubuntu-latest
        variables:
          - group: "terraformvar service connection"
        steps:
          - script: |
              set -e 

              terraform init -input = false
              terraform apply -auto-approve
              name: "Runterraformcmd"
              display_name: "Runterraformcmd"
              env:
                ARM_CLIENT_ID: $(ARM_CLIENT_ID)
                ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
                ARM_TENANT_ID: $(ARM_TENANT_ID)
                ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
                TF_VAR_imagebuild: $(tag)
